services:

  db:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: ${db_user}
      MARIADB_PASSWORD: ${db_pass}
      MARIADB_DATABASE: ${db_name}
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql

  server:
    build:
      context: .
    command: sh -c "npm install && npm start"
    volumes:
      - ./:/home/node/api
    ports:
      - "8001:8001"
    depends_on:
      - cache

  cache:
    image: redis:8.0-rc1-alpine
    ports:
      - "${cache_port}:${cache_port}"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${cache_pass}
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local

