services:

  db:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: ${db_user}
      MARIADB_PASSWORD: ${db_pass}
      MARIADB_DATABASE: ${db_name}
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
  server:
    build:
      context: .
    command: sh -c "npm install && npm start"
    volumes:
      - ./:/home/node/api
    ports:
      - "8001:8001"

